### ISSUE TITLE
Setup Putty Saved Sessions for SSM processing on Pre-Prod Data Pipeline Server

### ISSUE THREAD

**Issue by AramSimonian** [UKHomeOffice/dq-aws-migration#305] opened 2018-02-21 14:27 UTC
Setup Putty Saved Sessions for SSM processing on Pre-Prod Data Pipeline Server
 - [ ] Generate Data Ingest Linux key for WSR server saved Putty session: ***ssm_ssh_login***
 - [ ] Generate Data Ingest Linux key for WSR server saved Putty session: ***nats_ssh_login***
 - [ ] Generate Greenplum key for WSR server saved Putty session: ***greenplum_ssh_login***

**Comment by david-wirelab** [comment] 2018-03-01 09:20
Closing Dupe of: https://github.com/UKHomeOffice/dq-aws-transition/issues/330
https://github.com/UKHomeOffice/dq-aws-transition/issues/329

**Closed as completed by david-wirelab** 2018-03-01 09:20 UTC
Labels: DQ Data Pipeline, DQ Tranche 1, Production SSM processing
